sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: O9DGP3OCgwArHoobAKX44oNmtsHvf6UnjX0TO7RdsEI4M8TB1vqo5FAK+fOHs59UxNBClS3NL9uCq+gs+txnSFRB6+NGU1vUWtft1TyWUco4hHbV1QkwTm20GnbDvpQ6h+5rrBvLEA9s6O04xft+4Lpnd4EY0NPE4dmEGDw4lHNyKDOSjt6VUJxaspqQC7atZdciR2d3KL4a2dkcB56yq2NMfdGsL5olRJsGR0uqqg2D8ynaXmOX4n5JpWQSsrsMJw2lSoBcLVzgflORrarYFkcQbaUhL1u0S+ey4CFubGaw490J8ZCHT7/eFzBXD8sGWco6NfJyab1NBZw3sIVh9zZJ34egoF2IsawZoKh4EGl4aInBvUxdoh45TID6VezC6/BdxhaqEUxJRfZpq4sK3Y8ZCwxeHgees81Ca1ltLLGWke93vimCWNADShSNh2OJe7/jeCsf7L7wuC86DGvGw8v9gD9A0YqNuZ4Wnjjy3KDFv29gGKl8ldgq8V0RZchQt5FC4gfZlP6Cux1DQwnDHZvhe6Udf0oENTUHXharpVdNmIHRDBYB+cLaZUu6chOi6gnCTUfQ/bS2u9g5t5yL/hh4IVsmXZRjWBrs1mcPuXIAAHQ7WqhYZjCHpeQJ0ENC71d88LkIiS5qKe+B0EZ7dbbdU7hQAToTy8WrykIFpxc=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: fDSXYZ9w/hKPyMSh2eTkQIlGVuqXpUMZRjC0+nym5nXMz0aDV32x3g4DEnQ0awhmEQWtYk7SgyP8jXsTygQZKlYtX3g6qRiZozfxYcrKUgnitOQ0OiXRwTRlzqQEjwvA2XnZ0+VII13vkFCcOZO1tfLev24WzIZbAmE+up5kzzMuBjaU1p/OZ/FyM3QIrJllvQuOMwkMWcERqBiYch3armzFw55KfkHQo9TFHMoFp8O5Id8ZyVXg5LZyvSJPzPBzm6jt/bMGx549QOASegToFg0T3P5tgm38qyYLsV7JrWf5wuqYJDDObUkAaSWcm2rkuENed6xTuLaGYGEAdtLh58Sk8yv2tKFxnJBspsEe5RE3S498dkfR6RZADqN2YfmpZ9OAW1VqjIvkOOFIm+AmOYTado0Ucovd9zhx4lX3ndrsf/JPmbUdURO/HB09iGLYdYugqk3fz08pn+PiCCt8ecm2c7Pd4pvXKacWZz5iRkJRwTvZn3spaaiRKZNb7WWO6o/6Gf7PMNlNyqGN0gtlXEslt8O3sPa8ceBM3gPZXOR/7EJGnOZldRhqqr47b9J+X3Uh/3lE3XMcNlx2QYLqsL8xCp6trJm/DAMmA5rj6OG8WL2l1l4BaP5kEm1Sm0eAjImUgv77UDYHiB//zabXX6VxotepIZYdKAvkYU3/cq8=
